####################################################
# DEFAULT CONFIGURATION
####################################################
default:
  app:
    name: 'DEVELOPX TEST'
    port: 3001

############################################
# ENVIRONMENT -> LOCAL
############################################


############################################
# ENVIRONMENT -> DEV
############################################

############################################
# ENVIRONMENT -> STAGING
############################################

############################################
# ENVIRONMENT -> PRODUCTION
############################################
